### ISSUE TITLE
Separate from jupyter perhaps?

### ISSUE THREAD

**Issue by m-anish** [botlabio/autonomio#1]
Should jupyter be separate from the core functionality/project? 

The way I see it, jupyter doesnt performs the role of an enabler, and can be part of a wrapper repository around it. So, the core functionality is contained in one repository that anyone can clone/test/tweak to their wish, and things like jupyter/docker/vagrant are wrapper functionalities. 

Of course, we might not need to do it right away, but as the code base gets more complex, we should think about this structure. 

Another reason would be to figure out how to invoke travis. In the case of the core repo, it should be a bunch of sanity (environment/dependency) tests, and functionality tests, and in the case of the wrapper repository it can be a bunch of deployment related tests - like docker or vagrant container builds. Those may include jupyter.

**Comment by mikkokotila** [comment]
I agree, let's eventually move to having two separate packages, one is just the core capability, and the other is the "wrapper" package with docker, where Jupyter is also included.

**Comment by mikkokotila** [comment]
For now I've removed Jupyter from the core package.

**Comment by m-anish** [comment]
Great. I guess when we start using 'github milestones' we can assign this a milestone. Lets keep this open for now if you're okay with it.

**Comment by m-anish** [comment]
Please close this once you create the new repo. Assigning to @mikkokotila
