### ISSUE TITLE
create example for using multiple columns in X for test and train

### ISSUE THREAD

**Issue by amitphan** [botlabio/autonomio#17]
CReate another example with syntaxes in readme where the user selects multiple columns from one of the sample data sets and the results are shown.

**Comment by mikkokotila** [comment]
Thanks! Find the [updated doc here](https://github.com/botlabio/autonomio/blob/master/docs/index.rst)

I'll provide the updated below here as well. 

from autonomio.commands import train, data

After that there are multiple ways you can input 'x' with single input:

```
train('text' ,'neg', data) # a single column where data is string

train(5, 'neg', data) # a single column by index

train(['quality_score'], 'neg', data) # a single column by label

```
And few more ways where you input a list for 'x':

```
train([1,5], 'neg', data) # a range of column index

train(['quality_score', 'reach_score'], 'neg', data) # set of column labels

train([1,2,4,6,18], 'neg', data) # a list of column index
```

There are a bunch of settings that you'd have to change accordingly, which in part is already discussed in #13 so you may find that interesting as well.  Would love hear what you think.

**Comment by mikkokotila** [comment]
closing this
