### ISSUE TITLE
Setting up hooks between backend and Javascript

### ISSUE THREAD

**Issue by mikkokotila** [botlabio/autonomio#18]
Given the progress we have with #16, it seems that the natural next step is to start setting up the API hooks between the javascript fronted (all the functionality is no there) and the python backend so we get a clear picture of what needs to be added. For example we may want to provide a dictionary format as an option for standard output and then the core codes would probably do the job as is otherwise.

**Comment by mikkokotila** [comment]
This looks very nice:

[Easy Webhooks for Python](https://github.com/robinhood/thorn)

**Comment by mikkokotila** [comment]
Another option would be to do something like this: 

https://github.com/jeffknupp/sandman

If we are going to have a docker container, then we might as well have a DB? Makes many things simpler and allows much bigger datasets to be handled.

**Comment by m-anish** [comment]
A point to keep in mind:

Prasenjit mentioned that if we host the frontend for demo purpose, it could be quite cumbersome bandwidth wise for the user to upload datasets via frontend, which could be quite large in size. 

Another approach could be to have pointers to datasets already present on the server. 

Note: this is for demo hosting only. For regular usage, the users have their own privately hosted server over a LAN or a high bandwidth connection.

**Comment by mikkokotila** [comment]
Yes! I think the right solution now is to provide the docker container and then let the user run it, and if provide a demo maybe we could just fix it to one dataset we are already hosting.

**Comment by mikkokotila** [comment]
Note that we might be able to pull this off just with ipython nbconvert to html. Let's see, will have some updates tomorrow. That would surely simplify things.

**Comment by mikkokotila** [comment]
As we are making great progress using php for POST requests and everything else native python, I'm closing this.
