### ISSUE TITLE
Include code coverage in tests

### ISSUE THREAD

**Issue by m-anish** [botlabio/autonomio#2]
Consider including code coverage metrics alongwith travis-ci. 

References:
-  https://github.com/z4r/python-coveralls
-  https://coveralls.io/

**Comment by mikkokotila** [comment]
Thanks a lot, and I agree this is a great idea! I got Travis working with "hello world" and now trying to add some basic test. Also I can see something on coveralls.io but still have to figure out how the run command is used with modules.

**Comment by mikkokotila** [comment]
I have an update for this. I think everything is more or less ok, but there is an issue with travis loading the plot libraries in its environment. I've created a new issues related to that > #10

**Comment by mikkokotila** [comment]
I've left only the most basic test (setup.py) for coverage while we figure out how to use the run command successfully with functions inside the module.

**Comment by m-anish** [comment]
I will look into this.

**Comment by mikkokotila** [comment]
Very much worth the read >

Testivus on Test Coverage 

http://www.artima.com/forums/flat.jsp?forum=106&thread=204677

**Comment by mikkokotila** [comment]
Thanks again for fixing this. I think we're off to a good start now as I just ran the first more serious test. We're not at code coverage 79% and there are quite a few very simple things that can take us at least to 90% without struggles.

**Comment by m-anish** [comment]
Should we close this? I think the intent was to start doing code coverage. Later issues with the coverage metrics themselves can be tracker in newer issues.

**Comment by mikkokotila** [comment]
Yes totally, closing now.
