### ISSUE TITLE
Travis moves to 16.04 test build (or both)

### ISSUE THREAD

**Issue by mikkokotila** [botlabio/autonomio#21]
Given that now we're locked in to 16.04 on the Docker after all the mindless struggles today. Will try to do this today or tomorrow.

**Comment by m-anish** [comment]
Check out https://github.com/botlabio/autonomio/pull/26. Travis builds on 16.04 with that pull request.

**Comment by m-anish** [comment]
Should we close this?

**Comment by mikkokotila** [comment]
As strange as it seems...yesterday the close button was not there! :)
