### ISSUE TITLE
Any comments on the Dockerfile?

### ISSUE THREAD

**Issue by mikkokotila** [botlabio/autonomio#23]
For now I'll post the whole file here for possible comments: 

```
FROM phusion/baseimage
CMD ["/sbin/my_init"]

WORKDIR /var/www/html/
ADD . /var/www/html/

RUN apt-get update
RUN apt-get install git -Y
RUN apt-get install python-pip -y
RUN apt-get install apache2 -y
RUN apt-get install php libapache2-mod-php php-mcrypt -y
RUN apt-get install python-tk -y

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install jinja2
RUN pip install jupyter

RUN python -m spacy download en

RUN chown www-data:www-data -R /var/www/html/
RUN service apache2 restart

EXPOSE 80
ENV NAME World

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN adduser --disabled-password --gecos "" autonomio 
RUN su autonomio
RUN cd
RUN jupyter notebook --ip 0.0.0.0 --no-browser --allow-root > /tmp/token.temp
RUN cat /tmp/token.temp | grep http | cut -d ':' -f2- | tr -d ' \n' > /tmp/url.txt
RUN cp -r /var/www/html/autonomio /home/autonomio/autonomio
```

**Comment by m-anish** [comment]
Y is uppercase

RUN apt-get install git -Y

**Comment by mikkokotila** [comment]
I guess it picks up 'y' as well given we're passing :) I'm just about to hit what might be a "final" build. Since yesterday I've gained some level of command of the docker approach. But yea I'll change all those to capital Ys.

**Comment by mikkokotila** [comment]
This is very strange. Just now when I start to build the container, I can no longer use any -y or -Y which means also the build will immediately fail. 

Seems like docker has issues with a lot of really basic stuff. I guess it's kind of to the cloud what windows was to the desktop. So you get *this*:

`
Removing intermediate container f202fcff093a
Step 6/26 : RUN apt-get install git -Y
 ---> Running in 31398495b5b5
E: Command line option 'Y' [from -Y] is not understood in combination with the other options.
The command '/bin/sh -c apt-get install git -Y' returned a non-zero code: 100
`

**Comment by mikkokotila** [comment]
LOL...the fix is to move the -y between apt-get and install (?!) from where we had it before which is at the end of the line after the package name.

**Comment by m-anish** [comment]
Mikko. You should really be using git to manage (not exhibit) your work :P

**Comment by m-anish** [comment]
> the fix is to move the -y between apt-get and install (?!) from where we had it before which is at the end of the line after the package name.

Is that so? 

Because it seemed to be working yesterday with the -y at the end.

**Comment by mikkokotila** [comment]
yea, but I can say docker is something else. It's the windows of cloud os I guess. Yesterday was a good prelude for the -y and other similar things. No functional tmux, no session, it seems that having an apache running on the container is not simple at all...other than that everything else is now ok. I guess at least that once Apache is running nicely as a service, that could be somehow replicated with Jupyter. If you have ideas, I'm all ears. It has init.d seems like and I can't blame the transition away from it...if you have experience in setting up init.d script for running a service...that would be amazing :)

**Comment by mikkokotila** [comment]
This leads to a much bigger question, which is the fact that the container has init.d. If I understood there is a way for us to opt for systemd, do you know how we can do it?

**Comment by m-anish** [comment]
I will give your docker env that you checked into the repo a spin on a test server and try a few things and let you know.

**Comment by mikkokotila** [comment]
To update, I will have this online all hopefully in the next 24 hours. As it stands, we did not find  way to have the container always start with both jupyter and apache running...not in this timeframe / resource at least. Instead we have start.sh which does it for you and as you would have to otherwise use the docker command, it seems like the net result is the same. I might have spend a few "extra" hours just trying to solve this in a way where there would be on script, without considering the benefits of controlling the user's namespace 100% as opposed to having them make docker command at some point :p.

**Comment by m-anish** [comment]
Reassigning to you @mikkokotila :)

**Comment by mikkokotila** [comment]
Ok this will close - new repo up and you've been added as a collaborator :)
