### ISSUE TITLE
Link this github repository updates to the slack channel

### ISSUE THREAD

**Issue by m-anish** [botlabio/autonomio#5]
Reference: https://github.com/integrations/slack

**Comment by mikkokotila** [comment]
great idea! 👍 this is done! I guess that makes this issue closed?

**Comment by m-anish** [comment]
I guess we can enable message details. A notification of a commit isnt very helpful when there arent much details associated. If this gets too noisy, we can always change that in the future.

**Comment by m-anish** [comment]
I am closing this since you seem to have enabled this functionality. Thanks.
