### ISSUE TITLE
Merge setup_on_<> scripts

### ISSUE THREAD

**Issue by m-anish** [botlabio/autonomio#7]
Ideally, do platform detection and merge the two setup_on_<> scripts into a single setup.sh

**Comment by mikkokotila** [comment]
Yea, that's much better. I guess in this case we want to test the package manager that is available, as rest should be the same? 

- apt
- brew
- yum

...what else?

**Comment by m-anish** [comment]
Yep. A basic package manager test is okay I guess. We can just do apt and yum for now, as even the schoolserver has moved to debian.

**Comment by sheepray** [comment]
A quick note. It would be nice to introduce couple lines of code to create a python _virtual env_ before install any python packages.

**Comment by mikkokotila** [comment]
Because we are providing the docker container and also as of this coming week we will give the pypi package, I think we can drop the setup script at this point and look at it again when we know what kind of effort installing from the pypi package takes in worst case. Closing this.
