### ISSUE TITLE
error handling for spacy en not being loaded

### ISSUE THREAD

**Issue by mikkokotila** [botlabio/autonomio#9]
Actually it's no longer an error in the last version, so we'll have to handle it by checking if the requested language (by default 'en') is available before trying to open it.

**Comment by m-anish** [comment]
+1 sounds good!

**Comment by m-anish** [comment]
@mikkokotila Is this good to be closed then?

**Comment by mikkokotila** [comment]
Yea, I've fixed it in the branch I'm working on.
